#ifndef MIPMSKSOLVER_GLOBAL_H
#define MIPMSKSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIPMSKSOLVER_LIBRARY)
#  define MIPMSKSOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIPMSKSOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIPMSKSOLVER_GLOBAL_H
