set MOSEK_HOME=
set MOSEK_HOME_LIB=
set MOSEK_HOME_BIN=
set MOSEK_VERSION=

REM Find cplex installation using system environement variable

REM TEMPLATE
REM if exist %MOSEK_XX_BINDIR%\mosek64_XX.dll (
	REM set MOSEK_HOME=%MOSEK_XX_INSTALLDIR%\tools\platform\win64x86
	REM set MOSEK_HOME_BIN=%MOSEK_XX_BINDIR%
	REM set MOSEK_HOME_LIB=%MOSEK_XX_BINDIR%
	REM set MOSEK_VERSION=XX
	REM goto :END
REM )

if exist %MOSEK_8_1_BINDIR%\mosek64_8_1.dll (
	set MOSEK_HOME=%MOSEK_8_1_INSTALLDIR%\tools\platform\win64x86
	set MOSEK_HOME_BIN=%MOSEK_8_1_BINDIR%
	set MOSEK_HOME_LIB=%MOSEK_8_1_BINDIR%
	set MOSEK_VERSION=_8_1
)

:END
set PATH=%PATH%;%MOSEK_HOME_BIN%