#ifndef MIPHIGHSSOLVER_GLOBAL_H
#define MIPHIGHSSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIPHIGHSSOLVER_LIBRARY)
#  define MIPHIGHSSOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIPHIGHSSOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIPHIGHSSOLVER_GLOBAL_H
