#ifndef MIPCBCSOLVER_GLOBAL_H
#define MIPCBCSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIPCBCSOLVER_LIBRARY)
#  define MIPCBCSOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIPCBCSOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIPCBCSOLVER_GLOBAL_H
