#ifndef MIPCPXSOLVER_GLOBAL_H
#define MIPCPXSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIPCPXSOLVER_LIBRARY)
#  define MIPCPXSOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIPCPXSOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIPCPXSOLVER_GLOBAL_H
