#ifndef MIPCLPSOLVER_GLOBAL_H
#define MIPCLPSOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIPCLPSOLVER_LIBRARY)
#  define MIPCLPSOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIPCLPSOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIPCLPSOLVER_GLOBAL_H
